### ISSUE TITLE
Elasticsearch 0.90 formula no longer exists

### ISSUE THREAD

**Issue by dideler** [FundingCircle/brewfiles#22]
It was removed in https://github.com/Homebrew/homebrew-versions/commit/abc8851b4c0bb7b92c82764b854d147687ad23ff

We'll need to either 
- [create our own tap](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-to-Create-and-Maintain-a-Tap.md) for this specific formula
- tap [Homebrew/homebrew-versions-unsupported](https://github.com/Homebrew/homebrew-versions-unsupported) or [Homebrew/homebrew-boneyard](https://github.com/Homebrew/homebrew-boneyard)  
  (whichever ends up hosting it; [I've created a PR against the former](https://github.com/Homebrew/homebrew-versions-unsupported/pull/1))

Do we have any plans to upgrade our version of Elasticsearch? The latest stable version at the time of writing is **2.1**. Assuming the project follows semantic versioning, we are running a non-production-ready version in production which is not receiving any bug & security backports as it's no longer maintained.

**Comment by lostie** [comment]
I suggest we use the 
> tap Homebrew/homebrew-versions-unsupported or Homebrew/homebrew-boneyard

for the time being and consider upgrading in the meanwhile.

**Comment by dideler** [comment]
[My PR got rejected with the suggestion of hosting our own tap.](https://github.com/Homebrew/homebrew-versions-unsupported/pull/1#issuecomment-168352033)

**Comment by dideler** [comment]
@FundingCircle/core could we have a `homebrew-elasticsearch` repo to host the old formula?

**Comment by sgerrand** [comment]
@dideler: :sparkles: https://github.com/FundingCircle/homebrew-elasticsearch :sparkles: 

The changes in #23 will fix this issue.

**Comment by sgerrand** [comment]
> Do we have any plans to upgrade our version of Elasticsearch? The latest stable version at the time of writing is 2.1. Assuming the project follows semantic versioning, we are running a non-production-ready version in production which is not receiving any bug & security backports as it's no longer maintained.

Valid points, but they fall outside the scope of this repository.

CC: @FundingCircle/infrastructure
