### ISSUE TITLE
Postgresql92 formula no longer exists

### ISSUE THREAD

**Issue by dideler** [FundingCircle/brewfiles#26]
The [postgresql92 formula](https://github.com/Homebrew/homebrew-versions/blob/d64172e3500e22b9f8419f35408af8f91613f570/postgresql92.rb) was removed in https://github.com/Homebrew/homebrew-versions/commit/e102cc897ae1330b021c10f128197546b29ac543

Either we host our own tap like we did for #22 or we rename [our existing tap](https://github.com/FundingCircle/homebrew-elasticsearch) to something more general and add it there. I'm in favour of the latter to minimize the number of repos we need for these situations.

**Comment by dideler** [comment]
If anyone needs to install `postgresql92` until this is fixed, you can run
```bash
brew install https://raw.githubusercontent.com/Homebrew/homebrew-versions/d64172e3500e22b9f8419f35408af8f91613f570/postgresql92.rb
```

**Comment by sgerrand** [comment]
@dideler: Thy will be done, behold the [`homebrew-mortuary`](https://github.com/FundingCircle/homebrew-mortuary).
